// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG14AmK4XqrBhDP04kZfmOslmD2Nr-LoQ',
    appId: '1:105536201986:web:375350d7c9c6dd90170e1b',
    messagingSenderId: '105536201986',
    projectId: 'test2-6e552',
    authDomain: 'test2-6e552.firebaseapp.com',
    storageBucket: 'test2-6e552.appspot.com',
    measurementId: 'G-PDGY3P9ZD9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMxQwMnTQFBvU8DJ5ez-orUg5AG79510',
    appId: '1:105536201986:ios:541484d7572c1521170e1b',
    messagingSenderId: '105536201986',
    projectId: 'test2-6e552',
    storageBucket: 'test2-6e552.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiMxQwMnTQFBvU8DJ5ez-orUg5AG79510',
    appId: '1:105536201986:ios:541484d7572c1521170e1b',
    messagingSenderId: '105536201986',
    projectId: 'test2-6e552',
    storageBucket: 'test2-6e552.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG14AmK4XqrBhDP04kZfmOslmD2Nr-LoQ',
    appId: '1:105536201986:web:30d62edacfb06ffe170e1b',
    messagingSenderId: '105536201986',
    projectId: 'test2-6e552',
    authDomain: 'test2-6e552.firebaseapp.com',
    storageBucket: 'test2-6e552.appspot.com',
    measurementId: 'G-HCMQHGWJQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDud4uH2AMd44v5nH1qaiRIjqaNAzn7lwA',
    appId: '1:105536201986:android:fe8f2a6d88975e10170e1b',
    messagingSenderId: '105536201986',
    projectId: 'test2-6e552',
    storageBucket: 'test2-6e552.appspot.com',
  );

}